name: Docker Image CI

on:
  push:
    tags:
      - 'v*'         # Match any tag starting with 'v'
      - '*'          # Match any tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Set environment variable
    - name: Set environment variable
      run: echo "VITE_APP_API_URL=${{ secrets.VITE_APP_API_URL }}" >> $GITHUB_ENV

      # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/admin-parcel-locker"
        TAG="${GITHUB_REF#refs/tags/}"
        echo "Environment variable: $VITE_APP_API_URL"
        docker build --build-arg VITE_APP_API_URL=$VITE_APP_API_URL -f Dockerfile.prod -t $IMAGE_NAME:$TAG .

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/admin-parcel-locker"
        TAG="${GITHUB_REF#refs/tags/}"
        docker push $IMAGE_NAME:$TAG
