"""Add recipient table

Revision ID: 2a3708950352
Revises: 7d27676e3738
Create Date: 2024-11-13 18:30:54.300375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a3708950352'
down_revision: Union[str, None] = '7d27676e3738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient',
    sa.Column('recipient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.user_id'], ),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    op.create_index(op.f('ix_recipient_profile_id'), 'recipient', ['profile_id'], unique=False)
    op.create_index(op.f('ix_recipient_recipient_id'), 'recipient', ['recipient_id'], unique=False)
    op.alter_column('order', 'order_status',
               existing_type=postgresql.ENUM('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               type_=sa.Enum('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'Packaging'::order_status"))
    op.drop_constraint('order_recipient_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'recipient', ['recipient_id'], ['recipient_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_recipient_id_fkey', 'order', 'profile', ['recipient_id'], ['user_id'])
    op.alter_column('order', 'order_status',
               existing_type=sa.Enum('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               type_=postgresql.ENUM('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'Packaging'::order_status"))
    op.drop_index(op.f('ix_recipient_recipient_id'), table_name='recipient')
    op.drop_index(op.f('ix_recipient_profile_id'), table_name='recipient')
    op.drop_table('recipient')
    # ### end Alembic commands ###
