"""Update status

Revision ID: 3208d8ac45f1
Revises: 6c529dd0f1de
Create Date: 2024-11-08 14:50:07.690663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3208d8ac45f1'
down_revision: Union[str, None] = '6c529dd0f1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'order_status',
               existing_type=postgresql.ENUM('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               type_=sa.Enum('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'Packaging'::order_status"))
    op.add_column('parcel', sa.Column('parcelType', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parcel', 'parcel_type', ['parcelType'], ['parcel_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parcel', type_='foreignkey')
    op.drop_column('parcel', 'parcelType')
    op.alter_column('order', 'order_status',
               existing_type=sa.Enum('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               type_=postgresql.ENUM('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'Packaging'::order_status"))
    # ### end Alembic commands ###
