"""grand update

Revision ID: 7d27676e3738
Revises: 4c6869c10adf
Create Date: 2024-11-13 16:26:15.206038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d27676e3738'
down_revision: Union[str, None] = '4c6869c10adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipient_profile_id', table_name='recipient')
    op.drop_index('ix_recipient_recipient_id', table_name='recipient')
    op.drop_table('recipient')
    op.alter_column('order', 'order_status',
               existing_type=postgresql.ENUM('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               type_=sa.Enum('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'Packaging'::order_status"))
    op.create_foreign_key(None, 'order', 'profile', ['recipient_id'], ['user_id'])
    op.drop_column('order', 'warnings')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('warnings', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.alter_column('order', 'order_status',
               existing_type=sa.Enum('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               type_=postgresql.ENUM('Completed', 'Canceled', 'Ongoing', 'Delayed', 'Expired', 'Packaging', name='order_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'Packaging'::order_status"))
    op.create_table('recipient',
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', postgresql.ENUM('Male', 'Female', 'Prefer not to respond', name='gender_recipient'), autoincrement=False, nullable=True),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.user_id'], name='profile_id_of_recipient'),
    sa.PrimaryKeyConstraint('recipient_id', name='recipient_pkey')
    )
    op.create_index('ix_recipient_recipient_id', 'recipient', ['recipient_id'], unique=False)
    op.create_index('ix_recipient_profile_id', 'recipient', ['profile_id'], unique=False)
    # ### end Alembic commands ###
