"""change address to nullable

Revision ID: bbde89bb9c53
Revises: a91b7719485f
Create Date: 2024-08-19 22:41:49.420030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbde89bb9c53'
down_revision: Union[str, None] = 'a91b7719485f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Prefer not to respond', name='gender_profile'),
               type_=sa.Enum('Male', 'Female', 'Prefer not to respond', name='gender_profile'),
               existing_nullable=True)
    op.alter_column('recipient', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipient', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Prefer not to respond', name='gender_recipient'),
               type_=sa.Enum('Male', 'Female', 'Prefer not to respond', name='gender_recipient'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('recipient', 'gender',
               existing_type=sa.Enum('Male', 'Female', 'Prefer not to respond', name='gender_recipient'),
               type_=postgresql.ENUM('Male', 'Female', 'Prefer not to respond', name='gender_recipient'),
               existing_nullable=True)
    op.alter_column('recipient', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profile', 'gender',
               existing_type=sa.Enum('Male', 'Female', 'Prefer not to respond', name='gender_profile'),
               type_=postgresql.ENUM('Male', 'Female', 'Prefer not to respond', name='gender_profile'),
               existing_nullable=True)
    # ### end Alembic commands ###
